# -*- coding: utf-8 -*-
"""ATM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSEOnI2XLSV3Y7rF5fJmkz2xYyEEkFR4
"""

class Atm:
    def __init__(self):
        self.pin = ''
        self.balance = 0
        self.menu()

    def menu(self):
        user_input = input("""
        HI, HOW CAN I HELP YOU?
        1. CREATE PIN
        2. CHANGE PIN
        3. CHECK BALANCE
        4. WITHDRAW MONEY
        5. EXIT

        Enter your choice: """)

        if user_input == '1':
            self.create_pin()
        elif user_input == '2':
            self.change_pin()
        elif user_input == '3':
            self.check_balance()
        elif user_input == '4':
            self.withdraw()
        else:
            print("Thank you for using ATM!")
            exit()

    def create_pin(self):
        self.pin = input("Create your PIN: ")
        self.balance = int(input("Enter initial balance: "))
        print("PIN created successfully!")
        self.menu()

    def change_pin(self):
        old_pin = input("Enter your current PIN: ")
        if old_pin == self.pin:
            new_pin = input("Enter new PIN: ")
            self.pin = new_pin
            print("PIN changed successfully!")
        else:
            print("Incorrect PIN! Unable to change.")
        self.menu()

    def check_balance(self):
        entered_pin = input("Enter PIN: ")
        if entered_pin == self.pin:
            print("Your balance is:", self.balance)
        else:
            print("Incorrect PIN!")
        self.menu()

    def withdraw(self):
        entered_pin = input("Enter PIN: ")
        if entered_pin == self.pin:
            amount = int(input("Enter amount to withdraw: "))
            if amount <= self.balance:
                self.balance -= amount
                print("Withdrawal successful! Remaining balance:", self.balance)
            else:
                print("Insufficient balance!")
        else:
            print("Incorrect PIN!")
        self.menu()


# Run ATM
Atm()